### ISSUE TITLE
Question: Icecast/Shoutcast protocol spec. Where to look for

### ISSUE THREAD

**Issue by Phaet** [cryptiksouls/icecast-shoutcast-metadata-grabber#1]
Hi, 
I am digging into streaming radios since a while and found your fine implementation of a metadata grabber.
I am looking for a protocol spec for streaming radios an especially for the metadata, but can't find any info at neither Icecast and Shoutcast.
Could you perhaps give me a hint where to look for such info?
Thank you very much.

**Comment by cryptiksouls** [comment]
I remember I had trouble finding info about the protocol when I wrote the
service worker script, but I made some notes.

Here's how it works:

The client request must include the header "icy-metadata:1". If this header is present the server will return an "icy-metaint" header (which has a
default value of 8192). The value of this header tells you the number of bytes that will be in each mp3 block which is sent, so if the header value is 8192 then the first 8192 bytes you receive will be mp3 data and then the metadata will be inserted.

The metadata is encoded as a uint8 byte array. The first byte of the metadata indicates the length of the metadata string as a factor of 16, eg if the first byte is 5 then the metadata will be (16 * 5 =) 80 bytes long.
After this the next 8192 bytes will be mp3 data and then the process repeats. Any unused bytes at the end of the metadata string will be padded as zeros, so if the actual metadata string was 70 bytes long the final 10
bytes would each be a zero. If there is no metadata then the first byte will be zero.

Once you have split the metadata from the mp3 data then it's just a case of converting the uint8 array back to ascii to get the metadata string.

Hope I've explained that clearly, let me know if you need more info.
